// This file is generated by build.rs. Do not edit by hand.

#[test]
fn test_error() { assert_cli_test("tests/fixtures/error.c02", ExpectedOutcome::Failure); }

#[test]
fn test_func_mismatch() { assert_cli_test("tests/fixtures/func_mismatch.c02", ExpectedOutcome::Failure); }

#[test]
fn test_scoping() { assert_cli_test("tests/fixtures/scoping.c02", ExpectedOutcome::Failure); }

#[test]
fn test_semantic_errors() { assert_cli_test("tests/fixtures/semantic_errors.c02", ExpectedOutcome::Failure); }

#[test]
fn test_type_error() { assert_cli_test("tests/fixtures/type_error.c02", ExpectedOutcome::Failure); }

#[test]
fn test_type_error_call() { assert_cli_test("tests/fixtures/type_error_call.c02", ExpectedOutcome::Failure); }

#[test]
fn test_undeclared() { assert_cli_test("tests/fixtures/undeclared.c02", ExpectedOutcome::Failure); }

#[test]
fn test_valid() { assert_cli_test("tests/fixtures/valid.c02", ExpectedOutcome::Success); }

