use std::env;
use std::ffi::OsStr;
use std::fs;
use std::path::PathBuf;

fn sanitize_test_name(name: &str) -> String {
    let mut out = String::new();
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        out.insert(0, '_');
    }
    out
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let fixtures_dir = manifest_dir.join("tests/fixtures");
    let generated_path = manifest_dir.join("tests/cli/generated_cli_tests.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=tests/fixtures");

    if let Some(parent) = generated_path.parent() {
        fs::create_dir_all(parent).expect("failed to create generated tests directory");
    }

    let mut entries = fs::read_dir(&fixtures_dir)
        .unwrap_or_else(|e| panic!("failed to read fixtures directory {}: {}", fixtures_dir.display(), e))
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension() == Some(OsStr::new("c02")))
        .collect::<Vec<_>>();

    entries.sort();

    let mut generated = String::new();
    generated.push_str("// This file is generated by build.rs. Do not edit by hand.\n\n");
    for path in entries {
        let file_stem = path.file_stem().unwrap().to_string_lossy();
        let test_name = sanitize_test_name(&file_stem);
        let fixture_path = path
            .strip_prefix(&manifest_dir)
            .unwrap()
            .display()
            .to_string()
            .replace('\\', "/");
        let expected = if file_stem.starts_with("valid") {
            "ExpectedOutcome::Success"
        } else {
            "ExpectedOutcome::Failure"
        };

        generated.push_str(&format!(
            "#[test]\nfn test_{}() {{ assert_cli_test(\"{}\", {}); }}\n\n",
            test_name, fixture_path, expected
        ));
    }

    fs::write(&generated_path, generated)
        .unwrap_or_else(|e| panic!("failed to write generated tests {}: {}", generated_path.display(), e));
}
