    ; --- Run the Application ---
    JSR _main       ; Jump to the main function generated by compiler

    ; --- Catch-all if main ever returns ---
_exit:
    BRA _exit       ; Fallback infinite loop if STP isn't supported by hardware

; =============================================================================
; COMPILER GENERATED APPLICATION CODE
; =============================================================================
