
; =============================================================================
; RUNTIME STARTUP CODE
; =============================================================================

  .org $8000

_reset_handler:
    SEI             ; Disable interrupts during setup
    CLD             ; Clear decimal mode (crucial for 6502/65C02 sanity)
    LDX #$FF
    TXS             ; Initialize the hardware stack pointer to $01FF

    ; --- Clear Zero Page ---
    ; Clears completely from $00 to $FF
    LDX #$00        ; <-- Change from #$FF to #$00
    LDA #$00
.clear_zp:
    STA $00,X
    INX
    BNE .clear_zp   ; Wraps from $FF back to $00 to exit cleanly

    ; --- Initialize Software Stack Pointer (SP) ---
    ; software stack grows down from $0FFF in main RAM
    LDA #$FF
    STA SP          ; Low byte of $0FFF
    LDA #$0F
    STA SP+1        ; High byte of $0FFF 

    ; --- Run the Application ---
    JSR _main       ; Jump to the main function generated by compiler

    ; --- Catch-all if main ever returns ---
_exit:
    BRA _exit       ; Fallback infinite loop if STP isn't supported by hardware

; =============================================================================
; COMPILER GENERATED APPLICATION CODE
; =============================================================================

