  .include "reg.s"
  .include "c02_vectors.s"

  .org $8000

_reset_handler:
    SEI             ; Disable interrupts during setup
    CLD             ; Clear decimal mode (crucial for 6502/65C02 sanity)
    LDX #$FF
    TXS             ; Initialize the hardware stack pointer to $01FF

    ; --- Initialize Software Stack Pointer (SP) ---
    ; software stack grows down from $7FFF in main RAM
    LDA #$FF
    STA SP          ; Low byte of $7FFF
    LDA #$7F
    STA SP+1        ; High byte of $7FFF
    
    ; Copy SP directly to Frame Pointer (FP) for the initial root frame
    STA FP+1
    LDA #$FF
    STA FP

    ; --- Clear Zero Page User Space (Optional but clean) ---
    ; Clears from $40 to $FF so globals start at 0
    LDX #$40
    LDA #$00
.clear_zp:
    STA $00,X
    INX
    BNE .clear_zp

    ; --- Run the Application ---
    JSR _main       ; Jump to the main function generated by compiler

    ; --- Catch-all if main ever returns ---
_exit:
    BRA _exit       ; Fallback infinite loop if STP isn't supported by hardware

; =============================================================================
; COMPILER GENERATED APPLICATION CODE
; =============================================================================

