name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc python3 python3-pip valgrind
          pip install py65
      
      - name: Set up Haskell and Cabal
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.10.3'
          cabal-version: 'latest'

      - name: Update Cabal cache
        run: cabal update

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: make
      
      - name: Test Suite
        run: |
         python3 scripts/test.py
         make emu-test
      
      - name: LOC Report
        run: python3 scripts/loc.py