name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc python3 python3-pip valgrind
          pip install py65
      
      - name: Set up Haskell and Cabal
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.10.3'
          cabal-version: 'latest'

      - name: Configure Cabal repository
        run: |
          mkdir -p ~/.cabal
          cat > ~/.cabal/repositories.cfg << 'EOF'
          repository hackage.haskell.org
            url: https://hackage.haskell.org/
            secure: True
            root-keys: 07c59cb65787031cbb810701bd8ff5515f9ebe3e758d3b589d4a3a337f91dc08
                       2e8555dde16ebd8df076f1a396506f99fcfa541ee7a37b104d33177db735604c
                       8b9f40ae9b992d206ceabf2f4786226ae94036defc92874bd34ce6f1565d37b9
            key-threshold: 3
          EOF
          cabal update

      - name: Update Cabal cache
        run: cabal update

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up OCaml and Dune
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: '5.3'
          dune-cache: true

      - name: Install Dune
        run: |
          opam install -y dune
          echo "$(opam var bin)" >> "$GITHUB_PATH"

      - name: Build
        run: make

      - name: Test Suite
        run: |
         python3 scripts/test.py
         make emu-test
         make linker-test
      
      - name: LOC Report
        run: python3 scripts/loc.py
