name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc python3 python3-pip valgrind
          pip install py65

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: make

      - name: Test
        run: make test

      - name: Compile Examples
        run: |
            set -e
            for f in examples/*.c02; do
              echo "compiling $f"
              ./bin/cc02 --syntax-check-only "$f"
            done